# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'composeApp', :path => '../composeApp'
  pod 'TOCropViewController', '~> 2.6.1'

  # Pods for iosApp
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Minimum deployment target'ı 15.4'e yükselt
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.4
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.4'
      end
    end
  end
end