# Uncomment the next line to define a global platform for your project
platform :ios, '18.2'
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!


    pod 'composeApp', :path => '../composeApp'
     pod 'TOCropViewController', '~> 2.6.1'
  # Pods for iosApp

end